spring.application.name=ThreeThreadsMvp
# Dyno/Render Port Binding
server.port=${PORT:8080}

# Database Config (H2 In-Memory)
spring.datasource.url=jdbc:postgresql://ep-shy-forest-azvc25vy-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_8xdXt4KsYiun&sslmode=require&channelBinding=require
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8xdXt4KsYiun
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Allow large Base64 photo payloads in JSON
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
